services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: member_book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/member_book_db
      API_V1_STR: /members-book-service/v1
      PROJECT_NAME: Member Book Service
      BACKEND_CORS_ORIGINS: '["*"]'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
